TYPE = b'/Type'
ROOT = b'/Root'
PAGES = b'/Pages'
PAGE = b'/Page'
KIDS = b'/Kids'

RESOURCES = b'/Resources'
CONTENT = b'/Contents'
INFO = b'/Info'
COUNT = b'/Count'
SIZE = b'/Size'
ID = b'/ID'

MEDIA_BOX = b'/MediaBox'
CROP_BOX = b'/CropBox'
ROTATE = b'/Rotate'
DESTS = b'/Dests'
NAMES = b'/Names'
ENCRYPT = b'/Encrypt'

FLATE_DECODE = b'/FlateDecode'
